Repository softeerbootcamp4th/Team9-Podo-BE-1, pull requests merged in 2024-08, with the labels that each got.

#23 [Test] Redis, Java 선착순 통합/단위 테스트
  src/test/java/com/softeer/podoarrival/integration/event/ArrivalEventServiceTest.java
  src/test/java/com/softeer/podoarrival/unit/base/ArrivalEventMaxCountSchedulerBase.java
  src/test/java/com/softeer/podoarrival/unit/event/ArrivalEventComplexServiceTest.java
  src/test/java/com/softeer/podoarrival/unit/scheduler/ArrivalEventMaxCountSchedulerTest.java
Labels: enhancement

#29 [Feat] 선착순 응모가 완료되면 다음날 이벤트시간으로 카운트다운 되도록 수정
  build.gradle
  src/main/java/com/softeer/podoarrival/event/controller/ArrivalEventController.java
  src/main/java/com/softeer/podoarrival/event/scheduler/ArrivalEventInformationScheduler.java
  src/main/java/com/softeer/podoarrival/event/service/ArrivalEventReleaseService.java
  src/main/java/com/softeer/podoarrival/event/service/ArrivalEventReleaseServiceJavaImpl.java
  src/main/java/com/softeer/podoarrival/event/service/ArrivalEventReleaseServiceRedisImpl.java
  src/main/java/com/softeer/podoarrival/event/service/ArrivalEventService.java
  src/test/java/com/softeer/podoarrival/unit/scheduler/ArrivalEventInformationTest.java
Labels: enhancement

#28 [Fix] cors 에러 해결 및 https 연결 추가
  src/main/java/com/softeer/podoarrival/PodoArrivalApplication.java
  src/main/java/com/softeer/podoarrival/event/exception/ArrivalEventExceptionHandler.java
  src/main/java/com/softeer/podoarrival/test/exception/TestExceptionHandler.java
  src/main/resources/application.yml
Labels: enhancement, fixup

#30 [Fix] https 설정 제거
  src/main/java/com/softeer/podoarrival/PodoArrivalApplication.java
  src/main/resources/application.yml
Labels: fixup

#31 [Chore] 동기 지연테스트
  src/main/java/com/softeer/podoarrival/event/controller/ArrivalEventSyncController.java
  src/main/java/com/softeer/podoarrival/event/service/ArrivalEventSyncService.java
Labels: enhancement, test

#32 [Fix] 선착순 플래그 변수 및 테스트코드 수정
  src/main/java/com/softeer/podoarrival/event/scheduler/ArrivalEventInformationScheduler.java
  src/main/java/com/softeer/podoarrival/event/service/ArrivalEventReleaseService.java
  src/main/java/com/softeer/podoarrival/event/service/ArrivalEventReleaseServiceJavaImpl.java
  src/main/java/com/softeer/podoarrival/event/service/ArrivalEventReleaseServiceRedisImpl.java
  src/main/java/com/softeer/podoarrival/event/service/ArrivalEventService.java
  src/test/java/com/softeer/podoarrival/integration/event/ArrivalEventServiceTest.java
  src/test/java/com/softeer/podoarrival/unit/base/ArrivalEventBase.java
  src/test/java/com/softeer/podoarrival/unit/base/ArrivalEventInformationBase.java
  src/test/java/com/softeer/podoarrival/unit/event/ApplyArrivalEventTest.java
  src/test/java/com/softeer/podoarrival/unit/event/ArrivalEventComplexServiceTest.java
  src/test/java/com/softeer/podoarrival/unit/scheduler/ArrivalEventInformationTest.java
Labels: enhancement, fixup
